### ISSUE TITLE
hi,Chiaraplize,I had the following problem when I was running the code.

### ISSUE THREAD

**Issue by 1274739295** [Chiaraplizz/ST-TR#25]
Traceback (most recent call last):
  File "code/main.py", line 973, in <module>
    processor.start()
  File "code/main.py", line 885, in start
    self.train(epoch, save_model=save_model)
  File "code/main.py", line 529, in train
    for batch_idx, (data, label, name) in enumerate(loader):
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\ST-TR-master\code\st_gcn\feeder\feeder.py", line 142, in __getitem__
    if self.mirroring and bool(torch.bernoulli((0.5) * torch.ones(1))):
AttributeError: 'Feeder' object has no attribute 'mirroring'

Then I tried to output the training dataset:<torch.utils.data.dataloader.DataLoader object at 0x0000025C9B030CD0>
Train size:  10023

I hope you can help me solve this problem. Thanks.

**Comment by Chiaraplizz** [comment]
Hi, 

You can delete the following instruction: 
if self.mirroring and bool(torch.bernoulli((0.5) * torch.ones(1))):

since we are not using the self.mirroring attribute.

Chiara

**Comment by godkath** [comment]
Hi ,chiaraplizz,When I delete the instruction,it shows Pytorch TypeError: batch must contain tensors, numbers, dicts or lists….find nontype

**Comment by GedamuA** [comment]
> Hi ,chiaraplizz,When I delete the instruction,it shows Pytorch TypeError: batch must contain tensors, numbers, dicts or lists….find nontype


![image](https://user-images.githubusercontent.com/30148450/138544657-b612508f-3f25-4725-8fe5-e367bcc74abc.png)
