### ISSUE TITLE
IndexError: index 23667 is out of bounds for axis 0 with size 16560

### ISSUE THREAD

**Issue by jianghongcheng** [Chiaraplizz/ST-TR#27]
Traceback (most recent call last):
  File "/media/max/b/2021/FG_2021/ST-TR-master_FIRST/src/main.py", line 973, in <module>
    processor.start()
  File "/media/max/b/2021/FG_2021/ST-TR-master_FIRST/src/main.py", line 885, in start
    self.train(epoch, save_model=save_model)
  File "/media/max/b/2021/FG_2021/ST-TR-master_FIRST/src/main.py", line 529, in train
    for batch_idx, (data, label, name) in enumerate(loader):
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/max/b/2021/FG_2021/ST-TR-master_FIRST/src/st_gcn/feeder/feeder.py", line 127, in __getitem__
    data_numpy = np.array(self.data[index])
  File "/home/max/anaconda3/envs/GaitGraph/lib/python3.7/site-packages/numpy/core/memmap.py", line 331, in __getitem__
    res = super(memmap, self).__getitem__(index)
IndexError: index 23667 is out of bounds for axis 0 with size 16560

**Comment by jianghongcheng** [comment]
need to keep same data with label
