### ISSUE TITLE
hi, Chiaraplize, I had the following problem when I was running the code on kinetics-skeleton

### ISSUE THREAD

**Issue by NimbusDream** [Chiaraplizz/ST-TR#32]
torch.Size([32, 3, 150, 18, 2])
torch.Size([32, 3, 150, 18, 2])
Traceback (most recent call last):
  File "code/main.py", line 973, in <module>
    processor.start()
  File "code/main.py", line 885, in start
    self.train(epoch, save_model=save_model)
  File "code/main.py", line 540, in train
    output = self.model(data, label, name)
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data3/2019/liuyuan/ST-TR/code/st_gcn/net/st_gcn.py", line 267, in forward
    x = self.data_bn(x)
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/user/anaconda3/envs/st-tr/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 108 elements not 216

I hope you can help me sovle this problem and thank you so much!

**Comment by MintXDU** [comment]
Have you solved it?

**Comment by zuuumm-swt** [comment]
Recently I have the same problem, could you please tell me how to solve this problem thank you very much!!!

**Comment by Kuroshika** [comment]
Hi, I fixed it by modifying the config file _train.yaml_. 
I find the channel 6 but I think it should be 3. 

model_args:
  num_class: 60
  channel: 3
  window_size: 300
  num_point: 25

**Comment by zuuumm-swt** [comment]
> 

Thank you very much！
