### ISSUE TITLE
pickle data was truncated

### ISSUE THREAD

**Issue by khanonuvov** [Chiaraplizz/ST-TR#38]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

Why am I getting this error? @Chiaraplizz

**Comment by Compromise0805** [comment]
Hello, I wonder if you have solved this problem cause I meet the same problem. Thank you!
